def main_page(self, callback):

    cb_str = ''

    try:
        self.write('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html>')

        self.write(tracking_code)

        self.write('<head><title>Poe Price Info - Path of Exile Item Price Check</title>'
                   '<link rel="icon" type="image/png" href="/css/icon2.png">'
                   '<meta name="description" content="A simple tool to price check your items in path of exile by copy and paste">'
                   '<meta name="keywords" content="path of exile, price check, path of exile items">'
                   '<link rel="stylesheet" type="text/css" href="/css/item_server.css?' + str(int(time.time() * 1000)) + '" />'
                   + dfp_header +
                   '<script src="//code.jquery.com/jquery-1.10.2.js"></script>'
                   '<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>'
                   '<script type="text/javascript">$( document ).ready(function() {(function($) {var element = $(".follow_scroll"); originalY = element.offset().top; var topMargin = 20;element.css("position", "relative");$(window).on("scroll", function(event) {var scrollTop = $(window).scrollTop();element.stop(false, false).animate({top: scrollTop < originalY ? 0: scrollTop - originalY + topMargin},300);});})(jQuery);});</script>'
                   '<script type="text/javascript">window.onload = $(function () {$("document").ready(function () {var availableTags = [' + unames_str + '];$("#tags").on("keydown", function () {var newY = $(this).textareaHelper("caretPos").top + (parseInt($(this).css("font-size"), 10) * 1.5);var newX = $(this).textareaHelper("caretPos").left;var posString = "left+" + newX + "px top+" + newY + "px";$(this).autocomplete("option", "position", {my: "left top",at: posString});});$("#tags ").autocomplete({source: availableTags, minLength: 2});});});</script>'
                   '<script type="text/javascript"> function submitform() {var myshopids = document.getElementById("myshopids").value; localStorage.ppmyshopids = myshopids; document.getElementById("submitstash").click();}</script>'
                   '<script type="text/javascript"> function submitformsingle() {var myshopids = document.getElementById("myshopids2").value; localStorage.ppmyshopids = myshopids; document.getElementById("submitsingle").click();}</script>'
                   '<script type="text/javascript"> function submitformmanagestashes() {var myshopids = document.getElementById("myshopids3").value; localStorage.ppmyshopids = myshopids; var sessionid = document.getElementsByName("sessionid")[0].value; localStorage.ppsessionid = sessionid; document.getElementById("managestashes").click();}</script>'
                   '</head>'
                   '<body onload="if (localStorage.getItem(\'ppleague\') === null){document.getElementById(\'league\').value = \'Standard\';} else {document.getElementById(\'league\').value=localStorage.ppleague;} if (localStorage.getItem(\'ppauto\') === null){document.getElementById(\'auto\').value = \'auto\'; document.getElementById(\'auto2\').value = \'auto\'; } else {document.getElementById(\'auto\').value=localStorage.ppauto; document.getElementById(\'auto2\').value=localStorage.ppauto;} if (localStorage.getItem(\'ppmyshopids\') === null){document.getElementById(\'myshopids\').value = \'\';document.getElementById(\'myshopids2\').value = \'\';document.getElementById(\'myshopids3\').value = \'\';} else {document.getElementById(\'myshopids\').value=localStorage.ppmyshopids;document.getElementById(\'myshopids2\').value=localStorage.ppmyshopids;document.getElementById(\'myshopids3\').value=localStorage.ppmyshopids;} if (localStorage.getItem(\'ppsessionid\') === null){document.getElementsByName(\'sessionid\')[0].value = \'-1\';} else {document.getElementsByName(\'sessionid\')[0].value=localStorage.ppsessionid;} if (localStorage.getItem(\'ppmyaccounts\') === null){document.getElementById(\'myaccounts\').value = \'\';document.getElementById(\'myaccounts2\').value = \'\';} else {document.getElementById(\'myaccounts\').value=localStorage.ppmyaccounts;document.getElementById(\'myaccounts2\').value=localStorage.ppmyaccounts;} ">'
                   '<div id="fb-root"></div><script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id;js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";fjs.parentNode.insertBefore(js, fjs);}(document, "script", "facebook-jssdk"));</script>'
                   '<div class="wrapperall group">'
                   '<div class="content"><table style="width:730px">'
                   '<tr><td background="/css/logo.png" style="width:726px;height:115px;background-repeat:no-repeat;background-position:center;background-size:23%;" colspan="3"></td></tr>'
                   #'<tr><td colspan="4" background="/css/fire2.png"><p class="header">Your support helps</p></td></tr>'
                   '<tr><div class="fb-like" data-href="https://www.facebook.com/poepriceinfo" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>'
                   '&nbsp;<a href="https://twitter.com/slugspanker" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @slugspanker</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?"http":"https";if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document, "script", "twitter-wjs");</script>'
                   # '&nbsp;<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.poeprice.info" data-via="slugspanker">Tweet</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?"http":"https";if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document, "script", "twitter-wjs");</script> '
                   '<td colspan="3">'
                   # '<p><span><font color=red size=+1>Due to owner\' s vacation during Mar 12-24, 2017. Any unexpected unavailability will be restored ASAP after the period of time.</font></span></p>'
                   '<p><span>A simple tool to price check your items in path of exile by "copy and paste". It is that simple!</span></p><p>Support Google Chrome, Firefox and Safari</p>'
                   '<p><a class="boxed" href="/help">Help Page</a></p></td></tr>'
                   '<tr><td><br/><p>'
                   + paypal_code + '</p><br/></td>'
                   '<td><p>Your help means a lot to us!</p></td><td><p><a href="https://www.patreon.com/bePatron?u=5966037" data-patreon-widget-type="become-patron-button">Become a Patron!</a><script async src="https://c6.patreon.com/becomePatronButton.bundle.js"></script></p></td></tr>'     
                   '<tr style="height:40px;"><td style="width:33%"></br><p><a class="boxed2" href="#pricesingleitem">Price Single Item</a></p></br></td>'
                   '<td style="width:33%"></br><p><a class="boxed2" href="#priceastash">Price A Stash</a></p></br></td>'
                   '<td style="width:34%"></br><p><a class="boxed2" href="#priceallstashes">Price All Stashes</a></p></br></td></tr>'
                   '<tr></tr><tr style="height:40px;"><td style="width:33%"></br><p><a class="boxed2" href="#pricemyshop">Price A Shop</a></p></br></td>'
                   '<td style="width:33%"></br><p><a class="boxed2" href="/uniqueprices?Standard">T1 Uniques ST League</a></p></br></td>'
                   '<td style="width:34%"></br><p><a class="boxed2" href="/uniqueprices?Hardcore">T1 Uniques HC League</a></p></br></td></tr>'
                   '<tr></tr><tr style="height:40px;"><td style="width:33%"></br><p><a class="boxed2" href="/uniqueitempages/Alluniqueitems.html">All Uniques</a></p></br></td>'
                   '<td style="width:33%"></br><p><a class="boxed2" href="/stats/dataviz.html">Data Viz</a></p></br></td>'
                   '<td style="width:33%"></br><p><a class="boxed2" href="#pricetradetext">Price Trade Whisper</a></p></br></td></tr>'
                   '<tr></tr><tr style="height:40px;"><td style="width:33%"></td><td style="width:33%"></br><p><a class="boxed2" href="https://www.patreon.com/poeprices" target="_blank">Our Effort </a><font color="red">(new)</font></p></br></td>'
                   '<td style="width:34%"></br><p></p></br></td></tr>'
                   '</table>'
                   '<table style="width:730px">'
                   '<tr style="height:30px;"></tr><tr></tr>'
                   '<tr><td colspan="3">' + ad_code2 + '</td></tr><tr></tr>'
                   '<tr style="height:30px;"></tr><tr></tr>' 
                   '<form action="/query" method="POST">' 
                   '<tr><td colspan="3"><a name="pricesingleitem"></a><p class="header">Price a single item</p></td></tr><tr></tr>'
                   '<tr><td colspan="3"><p><span><ul><li>To import an item, hover over it in game and press Ctrl+C</li><li>then click on the textarea below and press Ctrl+V</li></ul></span></p></td></tr>'
                   '</td></tr><tr><td colspan="3">' + link_ad + '</td></tr><tr><td colspan="3" >'
                   '<textarea id="tags" onClick="this.select();" spellcheck="false" name="itemtext" rows="11" style="color:#585858;background-color: #1a1b18;border:solid #20211E;resize: none;overflow: auto; width:98.8%;" placeholder="Paste item text here, or type a name"></textarea></td>'
                   '</tr><tr></tr>'
                   '<tr><td colspan="3"><p onmouseup="localStorage.ppleague=document.getElementById(\'league\').value; document.getElementById(\'auto2\').value=document.getElementById(\'auto\').value; localStorage.ppauto=document.getElementById(\'auto\').value;">'
                   '<span class="selectParent"><img src="/css/scroll-arrows.png" style="display: inline-block; vertical-align: middle;height=16px;width=16px;"> <select id="league" name="league">'
                   '<option value="' + active_leagues[0] + '" selected="selected">' + active_leagues[0] + '</option>'
                   +''.join(['<option value="' + lea + '">' + lea + '</option>' for lea in active_leagues[1:]])+
                   # '<option value="' + active_leagues[1] + '">' + active_leagues[1] + '</option>'
                   # '<option value="' + active_leagues[2] + '">' + active_leagues[2] + '</option>'
                   # '<option value="' + active_leagues[3] + '">' + active_leagues[3] + '</option>'
                   '</select> <select id="auto" name="auto"><option value="auto" selected="selected">auto</option><option value="manual">manual</option></select></span>'
                   ' <input class="firstpageButton" id="submitsingle" type="submit" name="submit" value="Submit" onClick="submitformsingle();"> '
                   '<input class="firstpageButton" type="reset" value="Reset"></p><input style="display:none;" class="shopid" type="text" id="myshopids2" name="myshops"></td></tr>'
                   '<tr></tr><tr><td colspan="3"><p>Ignore my own account names (comma separated): <br/> <input class="shopid" type="text" onClick="this.select();" id="myaccounts" name="myaccounts" placeholder="Optional (e.g.: abc, chris)" onchange="localStorage.ppmyaccounts = this.value; document.getElementById(\'myaccounts2\').value = this.value;"></p></td></tr><tr></tr>'
                   '</form>'
                   '<tr style="height:50px;"></tr><tr></tr>'
                   '<tr></tr><tr><td colspan="3">' + ad_code + '</td></tr><tr></tr>'
                   '<tr style="height:30px;"></tr><tr></tr>'
                   '<tr></tr><tr><td colspan="3"><a name="priceastash"></a><p class="header">Price each stash</p></td></tr>'
                   '<tr><td colspan="3"><p><span><ul>'
                   '<li>Click the links below for your league</li>'
                   '<li><font color="red">Input your account name (XXX) at the end of the URL (not your character\'s name. Shown on GGG webpage as Logged in as XXX)</font></li>'
                   '<li>Copy ALL the text from the new page, and paste it into the text area below</li>'
                   '<li>(Optional) Log in to your path of exile forum may be required</li>'
                   '<li>(Optional) Change "tabIndex=0" at the end of the URL to import other tabs</li>'
                   '<li>Generate forum post and update existing forum post by appending this stash tab</li>'
                   '<li><font color="red">Note: it may take quite long to finish when there are so many items. The page may be black, but it is processing. Patience is the key.</font></li>'
                   '</ul></span></p></td></tr></table>'
                   '<table style="width:730px"><tr><td colspan="4"></td><tr>'
                   '<td colspan="2" class="each_league"><p><a class="boxed" href="http://www.pathofexile.com/character-window/get-stash-items?league=Standard&tabs=1&tabIndex=0&accountName=" target="_blank">Standard</a></p></td>'
                   '<td colspan="2" class="each_league"><p><a class="boxed" href="http://www.pathofexile.com/character-window/get-stash-items?league=Hardcore&tabs=1&tabIndex=0&accountName=" target="_blank">Hardcore</a></p></td>'
                   '</tr>'
                   '<tr><td colspan="4"></td><tr>'
                   '<td colspan="2" class="each_league"><p><a class="boxed" href="http://www.pathofexile.com/character-window/get-stash-items?league=' + active_leagues[0] + '&tabs=1&tabIndex=0&accountName=" target="_blank">' + active_leagues[0] + '</a></p></td>'
                   '<td colspan="2" class="each_league"><p><a class="boxed" href="http://www.pathofexile.com/character-window/get-stash-items?league=' + active_leagues[1] + '&tabs=1&tabIndex=0&accountName=" target="_blank">' + active_leagues[1] + '</a></p></td></tr>'
                   '</tr>' +
                   ''.join(['<tr><td colspan="4"></td><tr>'
                   '<td colspan="2" class="each_league"><p><a class="boxed" href="http://www.pathofexile.com/character-window/get-stash-items?league=' + active_leagues[4] + '&tabs=1&tabIndex=0&accountName=" target="_blank">' + active_leagues[4] + '</a></p></td>'
                   '<td colspan="2" class="each_league"><p><a class="boxed" href="http://www.pathofexile.com/character-window/get-stash-items?league=' + active_leagues[5] + '&tabs=1&tabIndex=0&accountName=" target="_blank">' + active_leagues[5] + '</a></p></td></tr>'
                   '</tr>' if len(active_leagues) >= 6 else '']) +
                   '<form action="/submitstash" method="POST">'
                   '<tr><td colspan="4"><p><span class="status"><textarea spellcheck="false" name="stashitemtext" rows="11" style="color:#585858;background-color: #1a1b18;border:solid #20211E;resize: none;overflow: auto;width: 98.8%" placeholder="Paste stash item text here"></textarea><span></p></td></tr>'
                   '<tr></tr><tr><td colspan="4"><p>'
                   '<textarea cols="1" rows="1" style="display:none;" id="auto2" name="auto2"></textarea>'
                   'Ignore my own shop(s) (comma separated): <br/> <input class="shopid" type="text" onClick="this.select();" id="myshopids" name="myshops" placeholder="Optional (e.g.: 736605, 121223)" onchange="localStorage.ppmyshopids = this.value; document.getElementById(\'myshopids2\').value = this.value; document.getElementById(\'myshopids3\').value = this.value;"><br/><br/>'
                   '<input type="checkbox" name="uselist" value="uselist">list  '
                   '<input class="firstpageButton" id="submitstash" type="submit" name="submit" value="SubmitStash" onClick="submitform();"> '
                   '<input class="firstpageButton" type="reset" value="Reset"></p><input style="display:none;" class="shopid" type="text" id="myaccounts2" name="myaccounts"></td></tr></form>'
                   '<tr style="height:30px;"></tr><tr></tr>'
                   '<tr><td colspan="3">' + ad_code3 + '</td></tr>'
                   '<tr style="height:30px;"></tr>'
                   '<tr></tr><tr><td colspan="4"><a name="pricetradetext"></a><p class="header">Price trade text</p></td></tr><tr></tr>'
                   '<form action="/pricetradetext" method="POST">'
                   '<tr></tr><tr><td colspan="4"><p>Input a whisper text from poe.trade: <br/> <input type="text" class="tradetext" name="tradetext" placeholder=""><br/>This works with items in the premium stash tabs.<br/>'
                   '<input class="firstpageButton" type="submit" name="submit" value="PriceTradeText"></p></td></tr>'
                   '</form>'
                   '<form action="/managestashes" method="POST">'
                   '<tr></tr><tr></tr><tr><td colspan="4"><a name="priceallstashes"></a><p class="header">Price all stashes</p></td></tr><tr></tr>'
                   '<tr><td colspan="4"><ul>'
                   '<li>Pick a league, and Input <a class="pseudo" href="https://code.google.com/p/procurement/wiki/LoginWithSessionID" target="_blank">SessionId</a></li>'
                   '<li>Browse any stash tab in your stashes</li>'
                   '<li>Generate forum post with all included stash tabs</li>'
                   '<li>Update forum post by appending to the existing one</li>'
                   '</ul></td></tr>'
                   '<tr></tr><tr><td colspan="4"><p>'
                   '<span class="selectParent"><img src="/css/scroll-arrows.png" style="display: inline-block; vertical-align: middle;height=16px;width=16px;"> <select id="stashleague" name="league">'
                   '<option value="' + active_leagues[0] + '" selected="selected">' + active_leagues[0] + '</option>'
                   +''.join(['<option value="' + lea + '">' + lea + '</option>' for lea in active_leagues[1:]])+
                   # '<option value="' + active_leagues[1] + '">' + active_leagues[1] + '</option>'
                   # '<option value="' + active_leagues[2] + '">' + active_leagues[2] + '</option>'
                   # '<option value="' + active_leagues[3] + '">' + active_leagues[3] + '</option>'
                   '</select> <span class="status">Sessionid: </span> <input class="shopid" type="password" onClick="this.select();" name="sessionid"> '
                   '<input style="display:none;" class="shopid" type="text" id="myshopids3" name="myshops"><br/><br/>'
                   '<input class="firstpageButton" type="submit" name="submit" id="managestashes" value="ManageStash" onClick="submitformmanagestashes();"></tr></form>'
                   '<tr></tr><tr><td colspan="4"><a name="pricemyshop"></a><p class="header">Price a shop</p></td></tr><tr></tr>'
                   '<form action="/pricemyshop" method="POST">'
                   '<tr></tr><tr><td colspan="4"><p>Input your or other\' s shop thread id: <br/> <input type="text" class="shopid" name="shopthreadid" placeholder="(e.g.: 736605, 121223)"><br/><br/>'
                   '<input class="firstpageButton" type="submit" name="submit" value="PriceShop"><br/>This can take many minutes if there are many items.</p></td></tr>'
                   '</form>'
                   '<tr><td colspan="4"><p><span><ul><li>This is not a GGG site</li>'
                   '<li>It is for personal fun and is under construction</li>'
                   '<li>Appreciate your bug report at <a href="http://www.pathofexile.com/forum/view-thread/1216141" target="_blank" class="pseudo">here</a>'
                   '</ul><span></p></td></tr>'
                   '<tr style="height:800px;"></tr>'
                   '</table>'
                   '</div>' 
                   # '<div class="sidebar"><div class="box_small follow_scroll"><iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=8&l=ez&f=ifr&linkID=c39dc1213614808621e7988d9c1cecac&t=poeprices-20&tracking_id=poeprices-20" width="120" height="240" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe> </div> <br/>'
                   # '<div class="box follow_scroll"> <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=11&l=ez&f=ifr&linkID=114465f9d2d598aebc6aba0217f2d7b2&t=poeprices-20&tracking_id=poeprices-20" width="120" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe> </div></div>' 
                   '</div></body></html>')
    except:
        cb_str += 'error: ' + str(sys.exc_info()[0]) + '\n'

    callback(cb_str)